export const POST_DOCUMENTSDRS = "POST_DOCUMENTSDRS" 
export const GET_DOCUMENTSDRS = "GET_DOCUMENTSDRS"
export const SETLOADING = "SETLOADING"
export const DOCUMENTSDRS_ERROR = "DOCUMENTSDRS_ERROR"
export const DELETE_DOCUMENTSDRS = "DELETE_DOCUMENTSDRS"
export const EDIT_DOCUMENTSDRS = "EDIT_DOCUMENTSDRS"

